// <auto-generated />
using CarSell.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarSell.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190320054524_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarSell.Data.Classes.Araba", b =>
                {
                    b.Property<int>("arabaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aciklama");

                    b.Property<decimal>("arabaFiyat");

                    b.Property<int>("arabaKm");

                    b.Property<string>("arabaUrl");

                    b.Property<int>("arabaYili");

                    b.Property<int>("markaId");

                    b.Property<int>("musteriId");

                    b.Property<int>("renkId");

                    b.Property<int>("sehirId");

                    b.Property<int>("yakitId");

                    b.HasKey("arabaId");

                    b.HasIndex("markaId");

                    b.HasIndex("musteriId");

                    b.HasIndex("renkId");

                    b.HasIndex("sehirId");

                    b.HasIndex("yakitId");

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("CarSell.Data.Classes.ArabaMarka", b =>
                {
                    b.Property<int>("markaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("markaAd");

                    b.HasKey("markaId");

                    b.ToTable("ArabaMarkalar");
                });

            modelBuilder.Entity("CarSell.Data.Classes.ArabaRenk", b =>
                {
                    b.Property<int>("renkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("renkAd");

                    b.HasKey("renkId");

                    b.ToTable("ArabaRenkler");
                });

            modelBuilder.Entity("CarSell.Data.Classes.ArabaYakit", b =>
                {
                    b.Property<int>("yakitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yakitAd");

                    b.HasKey("yakitId");

                    b.ToTable("ArabaYakitlar");
                });

            modelBuilder.Entity("CarSell.Data.Classes.Musteri", b =>
                {
                    b.Property<int>("musteriId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("eMail");

                    b.Property<string>("kullaniciAdi");

                    b.Property<string>("kullaniciSifresi");

                    b.Property<string>("musteriAd");

                    b.Property<string>("musteriSoyad");

                    b.Property<int>("musteriTelNo");

                    b.HasKey("musteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("CarSell.Data.Classes.Sehir", b =>
                {
                    b.Property<int>("sehirId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sehirAd");

                    b.HasKey("sehirId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("CarSell.Data.Classes.Araba", b =>
                {
                    b.HasOne("CarSell.Data.Classes.ArabaMarka", "ArabaMarka")
                        .WithMany()
                        .HasForeignKey("markaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarSell.Data.Classes.Musteri", "Musteri")
                        .WithMany("Araba")
                        .HasForeignKey("musteriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarSell.Data.Classes.ArabaRenk", "ArabaRenk")
                        .WithMany()
                        .HasForeignKey("renkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarSell.Data.Classes.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("sehirId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarSell.Data.Classes.ArabaYakit", "ArabaYakit")
                        .WithMany()
                        .HasForeignKey("yakitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
